[versions]
# plugins
kotlin = "2.2.21"
changelog = "2.5.0"
intellijPlatform = "2.10.5"
kover = "0.9.3"
#libraries
configcat = "2.2.0"
kotlinx-serialization = "1.9.0"


[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
configcat-java = { module = "com.configcat:configcat-publicapi-java-client", version.ref = "configcat" }
serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }